### ISSUE TITLE
automatic page refresh

### ISSUE THREAD

**Issue by rayjanoka** [rajnandan1/kener#16]
hi, I took this for a test drive today. It is very nice! 

One thing I noticed was that the page doesn't refresh itself when the monitor status or incident changes and it requires a manual refresh of the page to see the update. Is this something that you are considering adding in the future?

thanks! -Ray

**Comment by rajnandan1** [comment]
Hi ray

I am happy you liked it

Auto refresh is off or is not implemented because it is a server rendered page. And if you look at majority of the status pages they are also like this. 

What I can do is add a flag in site.yaml (using sockets or HTTP polls) to enable it but I feel it is not a necessity. 

Let me know if you still feel it is needed. I will get it implemented but might take time.
